### ISSUE TITLE
Error while predicting

### ISSUE THREAD

**Issue by bayvirus** [sh1r0/caffe-android-demo#12] opened 2015-11-30 09:04 UTC
Hi
When i'm predicting a sample image an error throwing like this. I'm using a caffe model made by Nvidia Digits and googleNet net.

11-30 10:54:52.878: D/stderr(22880): [WARNING
11-30 10:54:52.878: D/stderr(22880): ] Unknown layer name data
11-30 10:54:52.879: A/libc(22880): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 22914 (AsyncTask #1)
11-30 10:54:52.879: A/libc(22880): Send stop signal to pid:22880 in void debuggerd_signal_handler(int, siginfo_t, void)
11-30 10:55:03.785: D/GraphicBuffer(22880): create handle(0x6084a2e0) (w:704, h:324, f:1)
11-30 10:55:03.790: D/dalvikvm(22880): threadid=13: interp stack at 0x63807000
11-30 10:55:03.790: D/dalvikvm(22880): init ref table
11-30 10:55:03.790: D/dalvikvm(22880): init mutex
11-30 10:55:03.807: D/GraphicBuffer(22880): create handle(0x63766e10) (w:736, h:1280, f:1)
11-30 10:55:03.834: D/GraphicBuffer(22880): create handle(0x637b3c98) (w:704, h:324, f:1)

**Comment by sh1r0** [comment] 2015-12-16 05:18
Duplicate of https://github.com/sh1r0/caffe-android-lib/issues/22.

**Closed by sh1r0** 2015-12-16 05:18 UTC
